# Import stuff

In [2]:
import numpy as np

# Rules

- Operations between multiple arrays are first checked for proper shape match
- Mathematical operators are applied element wise
- Reduction operations (mean, std, skew etc. ) are applied to whole array unless an axis is specifed
- Missing values propagate unless explicitly ignored

# Array Broadcasting

In [19]:
a = np.arange(25).reshape(5,5)
b = np.arange(16).reshape(4,4)
c = np.arange(5)
d = np.arange(5).reshape(5,1)

In [6]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
c

array([0, 1, 2, 3, 4])

In [20]:
d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
d.shape

(5, 1)

In [22]:
a + a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [23]:
a + b

ValueError: operands could not be broadcast together with shapes (5,5) (4,4) 

In [27]:
a + c # down stretch for c

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23],
       [20, 22, 24, 26, 28]])

In [28]:
# right stretch for c and down stretch for d
c + d

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])