# Import stuff

In [1]:
import numpy as np

# numpy arrays and types

In [4]:
a = np.array(list(range(1,5)))

In [5]:
a

array([1, 2, 3, 4])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int32')

In [8]:
b = np.array([5,6,7,8])

In [9]:
b

array([5, 6, 7, 8])

In [10]:
b.dtype

dtype('int32')

# floats

In [11]:
c = np.array([1.2,3.4,4.5])

In [12]:
c.dtype

dtype('float64')

In [13]:
c[0]

1.2

In [14]:
c[0] = 10

In [15]:
c

array([10. ,  3.4,  4.5])

In [16]:
c.shape

(3,)

## Number of dimensions

In [17]:
c.ndim

1

In [18]:
d = np.array([[1,2],[2,3]])

In [19]:
d.ndim

2

# Number of elements

In [20]:
c.size

3

In [21]:
d.size

4

# Element wise adding subtracting and so on

Vectorized operations instead of loops

In [22]:
a + b

array([ 6,  8, 10, 12])

In [23]:
a * b

array([ 5, 12, 21, 32])

In [24]:
a * 10

array([10, 20, 30, 40])

In [25]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

# Universal functions (ufuncs)

In [26]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# 2D array

In [28]:
d

array([[1, 2],
       [2, 3]])

In [27]:
d.shape

(2, 2)

In [29]:
d.size

4

In [30]:
d.ndim

2

In [31]:
d[0,0]

1

In [32]:
d[0,1]

2

In [33]:
d[0,0] = 10

In [34]:
d

array([[10,  2],
       [ 2,  3]])

# Slicing

In [35]:
d[0]

array([10,  2])

In [36]:
d[0:]

array([[10,  2],
       [ 2,  3]])

In [37]:
d[1:]

array([[2, 3]])

In [40]:
d[1:2]

array([[2, 3]])

Negative number in slicing:
- 1:-2 throw away the first element and the last 2 elements

In [43]:
a

array([1, 2, 3, 4])

In [42]:
a[-2:]

array([3, 4])

In [44]:
a[::2]

array([1, 3])

# indexing and Slicing in multiple dimensions

In [46]:
d

array([[10,  2],
       [ 2,  3]])

#### 1st row, multiple ways

In [51]:
d[0]

array([10,  2])

In [52]:
d[0,]

array([10,  2])

In [53]:
d[0,:]

array([10,  2])

In [45]:
d[0, 1:2]

array([2])

#### 2 row onward and 2 column onward

In [47]:
d[1:,1:]

array([[3]])

#### second column

In [48]:
d[:,1]

array([2, 3])

# quiz

![quiz 1](quiz1.png)

In [55]:
a = np.arange(25).reshape(5,5)

In [56]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
blues = a[1::2,0:4:2]

In [62]:
blues

array([[ 5,  7],
       [15, 17]])

In [64]:
red = a[:,1::2]

In [65]:
red

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [66]:
yellow = a[4]

In [67]:
yellow

array([20, 21, 22, 23, 24])

# Changing sliced data

In [69]:
a = np.array([1,2,3,4])

In [70]:
b = a[:2]

In [71]:
a

array([1, 2, 3, 4])

In [72]:
b

array([1, 2])

changes parent

In [73]:
b[0] = -1

In [74]:
a

array([-1,  2,  3,  4])

In [75]:
b

array([-1,  2])

# Copy array

In [76]:
b = a.copy()

In [77]:
b

array([-1,  2,  3,  4])