# Import stuff

In [1]:
import numpy as np

# do things

In [2]:
a = np.arange(6).reshape(2,3)

In [7]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
a.shape

(2, 3)

# What is axis
axis usually refers to the direction of dimension for example in (2, 3) axis 0 is 2 and axis 1 is 3 which refers to 2 rows and 3 columns.
We can also use negative numbers for axis.
- -1 for columns
- -2 for rows
- -3 for depth
- -4 for across the arrays (4th dim)

# sum whole array

In [4]:
a.sum()

15

In [5]:
a.prod()

0

# sum across rows

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
a.sum(axis=-2)

array([3, 5, 7])

In [8]:
a.sum(axis=0)

array([3, 5, 7])

# sum across columns

In [12]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
a.sum(axis=-1)

array([ 3, 12])

In [10]:
a.sum(axis=1)

array([ 3, 12])

# sum across depth (3d)

In [13]:
a = np.arange(16).reshape(2,2,4)

In [14]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [15]:
a.sum(axis=-3)

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [17]:
a.sum(axis=0)

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

# sum across arrays (4d)

In [18]:
a = np.arange(32).reshape(2,2,2,4)

In [19]:
a

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]],


       [[[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]]]])

In [20]:
a.sum(axis = -4)

array([[[16, 18, 20, 22],
        [24, 26, 28, 30]],

       [[32, 34, 36, 38],
        [40, 42, 44, 46]]])

In [21]:
a.sum(axis=0)

array([[[16, 18, 20, 22],
        [24, 26, 28, 30]],

       [[32, 34, 36, 38],
        [40, 42, 44, 46]]])

# compatability with pandas
pandas works with the same axis and also allows **axis=rows and axis=columns**

# memorizing axis

In [22]:
a = np.ones((5,6))

In [23]:
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
a.shape

(5, 6)

In [25]:
a.sum(axis=0).shape

(6,)

The axis that we specify goes away. eg in (5, 6) if we say **axis = 0** then **5** goes away and if we specify **axis=1** then **6** goes away