# Import stuff

In [1]:
import numpy as np

# do stuff

In [2]:
wdata = np.loadtxt('wind.data')

In [3]:
wdata

array([[61.  ,  1.  ,  1.  , ..., 12.58, 18.5 , 15.04],
       [61.  ,  1.  ,  2.  , ...,  9.67, 17.54, 13.83],
       [61.  ,  1.  ,  3.  , ...,  7.67, 12.75, 12.71],
       ...,
       [78.  , 12.  , 29.  , ..., 16.42, 18.88, 29.58],
       [78.  , 12.  , 30.  , ..., 12.12, 14.67, 28.79],
       [78.  , 12.  , 31.  , ..., 11.38, 12.08, 22.08]])

In [4]:
wdata.shape

(6574, 15)

---
Calculate the min, max and mean windspeeds and standard deviation of the windspeeds over all the locations and all the times (a single set of numbers for the entire dataset).

In [8]:
wspeeds = wdata[:,3:]

In [9]:
wspeeds.shape

(6574, 12)

In [11]:
wspeeds.min()

0.0

In [12]:
wspeeds.max()

42.54

In [13]:
wspeeds.mean()

10.22837377040868

In [14]:
wspeeds.std()

5.603840181095793

___
Calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days (a different set of numbers for each location)

In [17]:
wspeeds.min(axis=-2)

array([0.67, 0.21, 1.5 , 0.  , 0.13, 0.  , 0.  , 0.  , 0.  , 0.04, 0.13,
       0.67])

In [20]:
wspeeds.max(axis=0)

array([35.8 , 33.37, 33.84, 28.46, 37.54, 26.16, 30.37, 31.08, 25.88,
       28.21, 42.38, 42.54])

In [25]:
wspeeds.mean(axis = -2)

array([12.36371463, 10.64644813, 11.66010344,  6.30627472, 10.45688013,
        7.09225434,  9.7968345 ,  8.49442044,  8.49581838,  8.70726803,
       13.121007  , 15.59946152])

In [22]:
wspeeds.std(axis=0)

array([5.61918301, 5.26820081, 5.00738377, 3.60513309, 4.93536333,
       3.96838126, 4.97689374, 4.49865783, 4.16746101, 4.50327222,
       5.83459319, 6.69734719])

---
Calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day (a different set of numbers for each day)

In [30]:
wspeeds.min(axis=-1)

array([9.29, 6.5 , 6.17, ..., 8.71, 9.13, 9.59])

In [31]:
wspeeds.max(axis=1)

array([18.5 , 17.54, 18.5 , ..., 29.58, 28.79, 27.29])

In [32]:
wspeeds.mean(axis=-1)

array([13.09666667, 11.79833333, 11.34166667, ..., 14.89      ,
       15.3675    , 15.4025    ])

In [33]:
wspeeds.std(axis=1)

array([2.5773188 , 3.28972854, 3.50543348, ..., 5.51175108, 5.30456427,
       5.45971172])

---
Find the location which has the greatest windspeed on each day (an integer column number for each day).

In [49]:
wspeeds.argmax(axis=-1)

array([10, 10,  0, ..., 11, 11,  2], dtype=int64)

---
Find the year, month and day on which the greatest windspeed was recorded.

In [40]:
wspeeds.argmax()

25943

In [41]:
np.unravel_index(wspeeds.argmax(),wspeeds.shape)

(2161, 11)

In [42]:
wdata[2161][0:3]

array([66., 12.,  2.])

In [50]:
np.where(wspeeds == wspeeds.max())

(array([2161], dtype=int64), array([11], dtype=int64))

---
Find the average windspeed in January for each location.

In [53]:
mask = wdata[:,1] == 1
wspeeds[mask].mean(axis=-2)

array([14.86955197, 12.92166667, 13.29962366,  7.19949821, 11.67571685,
        8.05483871, 11.81935484,  9.5094086 ,  9.54320789, 10.05356631,
       14.55051971, 18.02876344])

# Bonus

Calculate the mean windspeed for each month in the dataset.  Treat January 1961 and January 1962 as *different* months. (hint: first find a way to create an identifier unique for each month. The second step might require a for loop.)

In [73]:
year = 61
res = []
for i in range(18*12):
    i = i%12 + 1
    mask = (wdata[:,[0,1]] == year,i)
    res.append(wspeeds[mask].mean())
    year += 1

IndexError: too many indices for array

Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 1 1961) for the first 52 weeks. This can be done without any for loop.

In [64]:
12%12 + 1

1

# Bonus Bonus

Calculate the mean windspeed for each month without using a for loop.
(Hint: look at `searchsorted` and `add.reduceat`.)